name: sync_resources
summary: Sync a Viash package's test resources to the local filesystem
description: |
  Sync a Viash package's test resources to the local filesystem based on the
  the `.info.test_resources` field in the `_viash.yaml` file. This is useful for
  testing and debugging purposes.
usage: |
  sync_resources
  sync_resources --input _viash.yaml --output .

# authors:
#   - __merge__: /src/_authors/robrecht_cannoodt.yaml
#     roles: [ author, maintainer ]
#   - __merge__: /src/_authors/dries_schaumont.yaml
#     roles: [ reviewer ]

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        alternatives: ["-i"]
        type: file
        description: "Path to the _viash.yaml project configuration file."
        default: _viash.yaml
  - name: Outputs
    arguments:
      - name: "--output"
        alternatives: ["-o"]
        type: file
        default: .
        direction: output
        description: "Path to the directory where the resources will be synced to."
  - name: Arguments
    arguments:
      - name: "--dryrun"
        type: boolean_true
        description: "Does not display the operations performed from the specified command."
      - name: "--exclude"
        type: "string"
        multiple: true
        description: Exclude all files or objects from the command that matches the specified pattern.
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
engines:
  - type: docker
    image: alpine:3
    setup:
      - type: apk
        packages:
          - bash
          - rclone
          - yq
      - type: docker
        run:
          - rclone config create s3 s3 anonymous=true
          - rclone config create gs gcs anonymous=true
runners:
  - type: executable
  - type: nextflow
